#!/usr/bin/env perl

use strict;
use warnings;
use 5.008_001;

use Pod::Usage;

use version; our $VERSION = 'v0.5.4';

use App::Memcached::CLI::Main;

if (__FILE__ eq $0) {
    main()
} else {
    return 1;
}

sub main {
    my $Cli_Class = 'App::Memcached::CLI::Main';
    my $params = $Cli_Class->parse_args;
    pod2usage(-verbose => 1) if $params->{help};
    pod2usage(-verbose => 2) if $params->{man};
    my $cli = $Cli_Class->new(%$params) or pod2usage(-verbose => 1);
    $cli->run;
}

__END__

=encoding utf-8

=head1 NAME

B<memcached-cli> - Interactive/Batch CLI for Memcached

=head1 SYNOPSIS

Run an interactive CLI:

    memcached-cli <HOST[:PORT] | /path/to/socket> [OPTIONS]
    memcached-cli --addr|-a <HOST[:PORT] | /path/to/socket> [OPTIONS]
    memcached-cli [OPTIONS]  # Connect to 127.0.0.1:11211

These above turns into interactive mode like below:

    memcached@SERVER:PORT>
    memcached@SERVER:PORT> \h    # show help
    memcached@SERVER:PORT> \d    # display slabs info

Run as batch script:

    memcached-cli [options] <command> [<args>]

Show Help/Manual:

    # For general usage
    memcached-cli -h|--help
    memcached-cli --man

    # For available commands
    memcached-cli help
    memcached-cli help <command>

=head1 DESCRIPTION

This script runs an interactive CLI or batch utility for Memcached.

In interactive mode, it connects to a specified Memcached server and
interactively executes each command you run.

In batch mode, you can execute any command which you can do in interactive mode.

=head1 COMMANDS

NOTE:

A couple of features of following commands derives from
L<memcached/memcached-tool|https://github.com/memcached/memcached/blob/master/scripts/memcached-tool>

=over 4

=item B<display|\d>

Displays slabs statistics.

This command comes from I<memcached/memcached-tool>.

=item B<stats|\s>

Shows general statistics of memcached server by C<stats> command.

Just like I<memcached/memcached-tool> does.

=item B<settings|config|\c>

Shows memcached server settings by C<stats settings> command.

Just like I<memcached/memcached-tool> does.

=item B<cachedump|dump|\cd> CLASS [NUMBER]

Shows keys and sizes and expiration times of some items in specified slab CLASS.

You can specify NUMBER of items to show.
Without NUMBER option, shows 20 items only by default.

=item B<detaildump|\dd>

Reports statistics about data access using KEY prefix. The default separator for
prefix is ':'.

If you have not enabled reporting at Memcached start-up, you can enable it by
command C<detail on>.

See man B<memcached(1)> for details.

=item B<detail> MODE

Enables or disables stats collection for C<stats detail dump> reporting.

MODE should be either "on" or "off" to enable or to disable.

=item B<get> KEY

Gets one item in memcached by specified KEY and shows its data.

=item B<set> KEY VALUE [EXPIRE [FLAGS]]

Stores data into memcached by specified KEY, VALUE and optional EXPIRE and FLAGS.

=item B<delete> KEY

Deletes one item in memcached by specified KEY.

=item B<flush_all|flush> [DELAY]

Invalidates all data in memcached by C<flush_all> command.

With DELAY option, invalidation is delayed for specified seconds.

See official documentation of I<memcached> for details.

=item B<version>

Shows memcahed server version.

=item B<quit|exit|\q>

Exits program in interactive mode.

=item B<help|\h> [COMMAND]

Shows available COMMANDs and summary of their usage.

With optional COMMAND argument, shows detailed information of it.

=back

=head1 OPTIONS

=over 4

=item B<-t|--timeout=Int>

Sets connection timeout. Default is 1 seconds.

=item B<-d|--debug>

Shows debug logs.

=back

=head1 SEE ALSO

L<App::Memcached::CLI::Main>,
B<memcached(1)>,
L<http://www.memcached.org/>

=head1 AUTHORS

YASUTAKE Kiyoshi E<lt>yasutake.kiyoshi@gmail.comE<gt>

=head1 LICENSE

Copyright (C) 2015 YASUTAKE Kiyoshi.

This library is free software; you can redistribute it and/or modify it under
the same terms as Perl itself.  That means either (a) the GNU General Public
License or (b) the Artistic License.

=cut

